# Generated by Django 4.1.2 on 2022-11-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='customercategory',
            options={'ordering': ['-id'], 'verbose_name': 'Categoria del cliente', 'verbose_name_plural': 'Categorías del cliente'},
        ),
    ]
